### ISSUE TITLE
Bulk Redactor is not Multi-threaded or using Parallel Workers

### ISSUE THREAD

**Issue by WPChrisG** [Nuix/Bulk-Redactor#1]
Hi,

Have been discussing this with Cameron Stiller. This utility does not use any parallel workers whereas in workstation the bulk redaction tool will use parallel workers.

Are we able to integrate in a similar way to https://github.com/Nuix/Redact-All-Pages

This mentions concurrency as a way to use multithreads

**Comment by camstillhere** [comment]
@JuicyDragon FYI

**Comment by camstillhere** [comment]
Customer also stated that workstation took 5 mins 53 seconds however doing via script was approx. 19 minutes

**Comment by camstillhere** [comment]
Looks like this section of code needs threading... 
https://github.com/Nuix/SuperUtilities/blob/556aebb178553b8e8b9299fdc5a39e3411aa0924/Java/src/main/java/com/nuix/superutilities/annotations/BulkRedactor.java

**Comment by JuicyDragon** [comment]
Check out new release which now supports configurable concurrency: https://github.com/Nuix/Bulk-Redactor/releases/tag/v1.3.0
